[package]
name = "raytracer"
version = "0.1.0"
authors = ["Jayden Chan <jaydencn7@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "inv_sqrt_bench"
harness = false

[dependencies]
rand = "0.7.0"
rayon = "*"
